### ISSUE TITLE
The passed generator was created on 'cpu' even though a tensor on cuda:0

### ISSUE THREAD

**Issue by theoldsong** [jdh-algo/JoyHallo#11]
The passed generator was created on 'cpu' even though a tensor on cuda:0 was expected. Tensors will be created on 'cpu' and then moved to cuda:0. Note that one can probably slighly speed up this function by passing a generator that was created on the cuda:0 device.
win10上搭建，生成的时候提示CPU创建passed generator，速度太慢了。10秒生成了半个小时，请教下，怎么能使用换成cuda提升速度？

**Comment by theoldsong** [comment]
还有，这个硬件要求是什么
4090，显存都20个G了，还是这么慢

**Comment by DBDXSS** [comment]
> 还有，这个硬件要求是什么 4090，显存都20个G了，还是这么慢

除了显存之外，还有一个比较重要的影响因素是显卡的算力，在a100上需要10*25/16*24/60=6.25(分钟)，这里指10s视频，25fps，每次生成16帧，每一轮需要24s，如果把step缩短到15，可以缩短到2.34分钟

**Comment by gushuaialan1** [comment]
> > > The passed generator was created on 'cpu' even though a tensor on cuda:0 was expected. Tensors will be created on 'cpu' and then moved to cuda:0. Note that one can probably slighly speed up this function by passing a generator that was created on the cuda:0 device. win10上搭建，生成的时候提示CPU创建passed generator，速度太慢了。10秒生成了半个小时，请教下，怎么能使用换成cuda提升速度？
> > 
> > 
> > 感谢您的反馈，我们解决了这个问题，您可以更新仓库获取最新结果。通过修改[`scripts/inference.py`](https://github.com/jdh-algo/JoyHallo/blob/00df485142a82ba34937282eb9e40985508bf677/scripts/inference.py#L275)可以解决该问题，速度大约提升5%。
> 
> 非常感谢，希望后期能优化下，让老百姓消费卡也能流畅运行和生产。再次感谢！

我在A100上测试，确实很慢，fp16的情况下占用了 19G左右的显存，gpu使用效率不高，应该有优化的空间。

**Comment by DBDXSS** [comment]
> > > The passed generator was created on 'cpu' even though a tensor on cuda:0 was expected. Tensors will be created on 'cpu' and then moved to cuda:0. Note that one can probably slighly speed up this function by passing a generator that was created on the cuda:0 device. win10上搭建，生成的时候提示CPU创建passed generator，速度太慢了。10秒生成了半个小时，请教下，怎么能使用换成cuda提升速度？
> > 
> > 
> > 感谢您的反馈，我们解决了这个问题，您可以更新仓库获取最新结果。通过修改[`scripts/inference.py`](https://github.com/jdh-algo/JoyHallo/blob/00df485142a82ba34937282eb9e40985508bf677/scripts/inference.py#L275)可以解决该问题，速度大约提升5%。
> 
> 非常感谢，希望后期能优化下，让老百姓消费卡也能流畅运行和生产。再次感谢！

我们最新的工作中有希望大幅度缩短运行时间，敬请期待😄

**Comment by DBDXSS** [comment]
> > > > The passed generator was created on 'cpu' even though a tensor on cuda:0 was expected. Tensors will be created on 'cpu' and then moved to cuda:0. Note that one can probably slighly speed up this function by passing a generator that was created on the cuda:0 device. win10上搭建，生成的时候提示CPU创建passed generator，速度太慢了。10秒生成了半个小时，请教下，怎么能使用换成cuda提升速度？
> > > 
> > > 
> > > 感谢您的反馈，我们解决了这个问题，您可以更新仓库获取最新结果。通过修改[`scripts/inference.py`](https://github.com/jdh-algo/JoyHallo/blob/00df485142a82ba34937282eb9e40985508bf677/scripts/inference.py#L275)可以解决该问题，速度大约提升5%。
> > 
> > 
> > 非常感谢，希望后期能优化下，让老百姓消费卡也能流畅运行和生产。再次感谢！
> 
> 我在A100上测试，确实很慢，fp16的情况下占用了 19G左右的显存，gpu使用效率不高，应该有优化的空间。

gpu利用率的问题您说的没错，确实还有许多优化空间，现在的模型设置是为了显存能满足大部分人的使用需求，如果想要进一步提升利用率，准入门槛会相应提升很多。
