### ISSUE TITLE
The semi-decoupled structure？

### ISSUE THREAD

**Issue by weisihao** [jdh-algo/JoyHallo#13]
Hello. It was not added "motion_scale" when merging. semi-decoupled structure was not used in the end？

**Comment by DBDXSS** [comment]
`motion_scale` is set to 1 default. It only affects the weights between different components.

**Comment by weisihao** [comment]
Thank you, I found it. May I ask, what is the difference in code between joyhallo and hallo？

**Comment by weisihao** [comment]
> The aggregation module is different.

I can't found aggregation module,can you mark the location?

**Comment by DBDXSS** [comment]
You can find it in [attention.py](https://github.com/jdh-algo/JoyHallo/tree/main/joyhallo/models/attention.py).
