### ISSUE TITLE
Hallo2 is out , will you update it to JoyHallo v2?

### ISSUE THREAD

**Issue by Semonxue** [jdh-algo/JoyHallo#15]

**Comment by DBDXSS** [comment]
Hello, we are currently not considering an upgrade to Hallo2. Instead, we are focusing on a brand-new project that will significantly reduce the size and runtime of audio-driven digital human models. We expect to share this exciting development with you soon.

**Comment by Semonxue** [comment]
> Hello, we are currently not considering an upgrade to Hallo2. Instead, we are focusing on a brand-new project that will significantly reduce the size and runtime of audio-driven digital human models. We expect to share this exciting development with you soon.

Thats cool! Can't wait for this.
