### ISSUE TITLE
请问如果想口型幅度稍微小一点可以调整什么参数?

### ISSUE THREAD

**Issue by WeizhenEricFang** [jdh-algo/JoyHallo#19]
用默认的参数生成的口型有些夸张,不真实和畸变. 请问该调整什么参数?

![image](https://github.com/user-attachments/assets/25043198-de49-46ed-98ec-9e235bec8ecb)
![image](https://github.com/user-attachments/assets/569e28d8-c172-4747-9c80-8cc1d64cdd88)
![image](https://github.com/user-attachments/assets/d0d734f5-55dd-4bad-9efa-052c2cb5d58c)
![image](https://github.com/user-attachments/assets/c90d5526-2bc0-4e17-bb97-0cfd0e3691ec)
![image](https://github.com/user-attachments/assets/e51861aa-3bae-41e9-acec-46db0b85168f)

**Comment by DBDXSS** [comment]
这种情况通常建议您尝试换一张图像，使用符合要求的嘴部微张、光线柔和的图像，或者您可以尝试修改`cfg_scale`和`inference_steps`
