### ISSUE TITLE
对开源的两个权重感到疑惑

### ISSUE THREAD

**Issue by piwawa** [jdh-algo/JoyHallo#2]
Hallo 模型和 JoyHallo 模型有什么具体区别？哪个是最好的？

模型 | 数据 | Huggingface | 京东云 | 描述
-- | -- | -- | -- | --
JoyHallo | jdh-hallo | JoyHallo | JoyHallo | 适用于JoyHallo模型
ch-Hallo | jdh-hallo | ch-Hallo | ch-Hallo | 适用于Hallo模型

**Comment by zhaojun060708** [comment]
ch-hallo是专门针对中文口型训练的
JoyHallo在原hallo模型基础上改进了网络结构，优化了训练和推理性能

**Comment by piwawa** [comment]
> ch-hallo是专门针对中文口型训练的，模型结构与hallo相同 JoyHallo在原hallo模型基础上改进了网络结构，优化了训练和推理性能

ch-hallo 就是 hallo 原版模型框架，用你们的 jdh-Hallo 数据集训练的权重？两个都是从头训练的权重吗？

**Comment by DBDXSS** [comment]
是的，ch-hallo 就是 hallo 原版模型框架，两个权重都是使用jdh-Hallo数据集训练后的权重。这里放置两个权重是为了方便大家使用和进行对比。您可以直接使用JoyHallo进行推理，推理效果和推理速度更好一些。

**Comment by DBDXSS** [comment]
> 是的，ch-hallo 就是 hallo 原版模型框架，两个权重都是使用jdh-Hallo数据集训练后的权重。这里放置两个权重是为了方便大家使用和进行对比。您可以直接使用JoyHallo进行推理，推理效果和推理速度更好一些。

我们调整了相关内容，避免大家产生相似困惑。
