### ISSUE TITLE
生成效果有点问题

### ISSUE THREAD

**Issue by hnsywangxin** [jdh-algo/JoyHallo#26]
感谢开源，试了下中文效果，非常棒，但是还有很多地方有瑕疵，比如生成的效果非常不稳定，很容易出现类似这样的图片，我裁剪的已经基本按照要求取做了
<img width="498" alt="截屏2024-11-22 16 57 43" src="https://github.com/user-attachments/assets/e525917a-8ff7-4088-bac0-cc51c7744e0b">
这是新闻联播主持人的，背景有花花绿绿的方块生成
<img width="497" alt="image" src="https://github.com/user-attachments/assets/a4f1c6f7-1dc3-4f63-b158-677f456e9742">
这个人穿的都是蓝色衣服，但是无缘无故出现类似手一样的东西出来
请问这种情况大概是什么原因导致的呢

**Comment by DBDXSS** [comment]
第一种情况有两个原因：1.背景较为复杂，并且训练集中相似样本较少；2.生成的时候，为了保持帧间一致性，使用上一次生成片段的后几帧作为下次的条件，导致误差逐渐变大，开始的时候可能只是几个噪点。

第二种情况是训练出现的伪影（鬼手）情况，这个是训练的时候会出现的，随着训练进行下去，这个情况必然会出现，可能是因为训练集中有部分手部视频导致的。

我们也在尝试解决这个问题，目前出现这两种情况最好的解决方式是换一个种子，再次尝试生成，我们试验过基本常识一到两次能解决这个问题。

**Comment by hnsywangxin** [comment]
好的，了解了，非常感谢
