### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by nopeiyu** [jdh-algo/JoyHallo#28]
请问你们stage2也是训练了30000轮吗？训练中各个阶段的模型效果怎么样，我用自有数据集训练15000轮后口型效果仍然比较差，和数据集有关系吗，你们的训练数据都是类似播报那种人不怎么动的视频吗，多谢

**Comment by DBDXSS** [comment]
也训练了30000轮，是类似播报那种人不怎么动的视频
