### ISSUE TITLE
inference script causes training to begin

### ISSUE THREAD

**Issue by linuxandchill** [jdh-algo/JoyHallo#3]
when running `sh joyhallo-infer.sh` it appears that a training process is kicked off

`09/16/2024 19:31:39 - ERROR - root - Failed to execute the training process: Error(s) in loading state_dict for Net:`

**Comment by DBDXSS** [comment]
This is not referring to the training process, but an error in thecheckpoint loading process. Which checkpoints are you using, ch-hallo or joyhallo?

**Comment by linuxandchill** [comment]
> This is not referring to the training process, but an error in thecheckpoint loading process. Which checkpoints are you using, ch-hallo or joyhallo?

using joyhallo, downloaded from huggingface:
`wget https://huggingface.co/spaces/jdh-algo/JoyHallo-v1/resolve/main/pretrained_models/joyhallo/net.pth`

**Comment by DBDXSS** [comment]
> > This is not referring to the training process, but an error in thecheckpoint loading process. Which checkpoints are you using, ch-hallo or joyhallo?
> 
> using joyhallo, downloaded from huggingface: `wget https://huggingface.co/spaces/jdh-algo/JoyHallo-v1/resolve/main/pretrained_models/joyhallo/net.pth`

Can you provide the complete log?

**Comment by linuxandchill** [comment]
i have been able to resolve this, seems that i didn't have the wav2vec model

am having another issues with CUDA but i will try to resolve. maybe a Docker container would help to include ?

**Comment by DBDXSS** [comment]
Glad to hear that. Thanks for your suggestion, we will consider adding the Docker container.
