### ISSUE TITLE
Gradio 推理后合成音频到视频时报错！

### ISSUE THREAD

**Issue by piwawa** [jdh-algo/JoyHallo#7]
```
Moviepy - Building video output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video output.mp4

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "/root/miniconda3/envs/comfy/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType
```

fps在调试时为正常25，相关代码：

```python
def tensor_to_video(tensor, output_video_file, audio_source, fps=25):
    """
    Converts a Tensor with shape [c, f, h, w] into a video and adds an audio track from the specified audio file.

    Args:
        tensor (Tensor): The Tensor to be converted, shaped [c, f, h, w].
        output_video_file (str): The file path where the output video will be saved.
        audio_source (str): The path to the audio file (WAV file) that contains the audio track to be added.
        fps (int): The frame rate of the output video. Default is 25 fps.
    """
    tensor = tensor.permute(1, 2, 3, 0).cpu(
    ).numpy()  # convert to [f, h, w, c]
    tensor = np.clip(tensor * 255, 0, 255).astype(
        np.uint8
    )  # to [0, 255]

    def make_frame(t):
        # get index
        frame_index = min(int(t * fps), tensor.shape[0] - 1)
        return tensor[frame_index]
    new_video_clip = VideoClip(make_frame, duration=tensor.shape[0] / fps)
    audio_clip = AudioFileClip(audio_source).subclip(0, tensor.shape[0] / fps)
    new_video_clip = new_video_clip.set_audio(audio_clip)
    new_video_clip.write_videofile(output_video_file, fps=fps, audio_codec='aac')
```

**Comment by DBDXSS** [comment]
您好，看起来像是moviepy出现了问题，可以尝试下面命令能否解决问题：
`pip install moviepy==1.0.3 numpy==1.26.4 --force-reinstall`

如果仍不能解决，可以按照以下步骤提供信息帮助我们定位您的问题：

1. 您是否对代码做出任何调整；
2. pip list；
3. 启动gradio命令的命令是什么；
4. 您的系统版本和显卡版本；
5. 如果方便的话，可以提供您的测试用例。

**Comment by piwawa** [comment]
1. 在推理函数 `def inference` 起始位置加了一个人脸检测的代码，已调试过没有bug

2. pip 包版本
```
$pip show numpy
Name: numpy
Version: 1.26.4

$pip show moviepy
Name: moviepy
Version: 1.0.3

$python -V
Python 3.10.14
```

3. 启动命令
```
JoyHallo# python scripts/app.py
``` 

4. 系统 manjaro，CUDA版本12.4
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

5. 测试用例

```python
import numpy as np
import torch
from moviepy.editor import VideoClip, AudioFileClip

def tensor_to_video(tensor, output_video_file, audio_source, fps=25):
    """
    Converts a Tensor with shape [c, f, h, w] into a video and adds an audio track from the specified audio file.

    Args:
        tensor (Tensor): The Tensor to be converted, shaped [c, f, h, w].
        output_video_file (str): The file path where the output video will be saved.
        audio_source (str): The path to the audio file (WAV file) that contains the audio track to be added.
        fps (int): The frame rate of the output video. Default is 25 fps.
    """
    print(f"FPS: {fps}")  # Debugging line to check fps value
    tensor = tensor.permute(1, 2, 3, 0).cpu().numpy()  # convert to [f, h, w, c]
    tensor = np.clip(tensor * 255, 0, 255).astype(np.uint8)  # to [0, 255]

    def make_frame(t):
        # get index
        frame_index = min(int(t * fps), tensor.shape[0] - 1)
        return tensor[frame_index]

    new_video_clip = VideoClip(make_frame, duration=tensor.shape[0] / fps)
    audio_clip = AudioFileClip(audio_source).subclip(0, tensor.shape[0] / fps)
    new_video_clip = new_video_clip.set_audio(audio_clip)
    new_video_clip.write_videofile(output_video_file, fps=fps, audio_codec='aac')

# Test the function
if __name__ == "__main__":
    # Create a dummy tensor for testing
    c, f, h, w = 3, 50, 64, 64
    dummy_tensor = torch.rand(c, f, h, w)
    output_video_file = "output.mp4" # 输出视频
    audio_source = "test.mp3" # 输入音频
    tensor_to_video(dummy_tensor, output_video_file, audio_source, fps=25)
```

**Comment by piwawa** [comment]
您好，我在两台不同的服务器上测试这个demo，都是这个结果，很怪。。

```
(cu118) [bingo06@zernithos test]$ python test.py
FPS: 25
Moviepy - Building video output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video output.mp4

Traceback (most recent call last):
  File "/home/bingo06/AIGC/test/test.py", line 36, in <module>
    tensor_to_video(dummy_tensor, output_video_file, audio_source, fps=25)
  File "/home/bingo06/AIGC/test/test.py", line 27, in tensor_to_video
    new_video_clip.write_videofile(output_video_file, fps=fps, audio_codec='aac')
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType
```

我注意到这里和你的不一样

```
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3  # 我的
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp4  # 你的
```

这是我用的输入参数，您那边有做过改动吗？

```python
# Test the function
if __name__ == "__main__":
    # Create a dummy tensor for testing
    c, f, h, w = 3, 50, 64, 64
    dummy_tensor = torch.rand(c, f, h, w)
    output_video_file = "output.mp4" # 输出视频
    audio_source = "/home/bingo06/AIGC/test/audio/openai_tts.wav" # 输入音频
    tensor_to_video(dummy_tensor, output_video_file, audio_source, fps=25)
```

**Comment by DBDXSS** [comment]
> 您好，我在两台不同的服务器上测试这个demo，都是这个结果，很怪。。
> 
> ```
> (cu118) [bingo06@zernithos test]$ python test.py
> FPS: 25
> Moviepy - Building video output.mp4.
> MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
> MoviePy - Done.
> Moviepy - Writing video output.mp4
> 
> Traceback (most recent call last):
>   File "/home/bingo06/AIGC/test/test.py", line 36, in <module>
>     tensor_to_video(dummy_tensor, output_video_file, audio_source, fps=25)
>   File "/home/bingo06/AIGC/test/test.py", line 27, in tensor_to_video
>     new_video_clip.write_videofile(output_video_file, fps=fps, audio_codec='aac')
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
>     return f(clip, *a, **k)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
>     return f(clip, *new_a, **new_kw)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
>     return f(clip, *a, **k)
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
>     ffmpeg_write_video(self, filename, fps, codec,
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
>     with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
>   File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 88, in __init__
>     '-r', '%.02f' % fps,
> TypeError: must be real number, not NoneType
> ```
> 
> 我注意到这里和你的不一样
> 
> ```
> MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3  # 我的
> MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp4  # 你的
> ```
> 
> 这是我用的输入参数，您那边有做过改动吗？
> 
> ```python
> # Test the function
> if __name__ == "__main__":
>     # Create a dummy tensor for testing
>     c, f, h, w = 3, 50, 64, 64
>     dummy_tensor = torch.rand(c, f, h, w)
>     output_video_file = "output.mp4" # 输出视频
>     audio_source = "/home/bingo06/AIGC/test/audio/openai_tts.wav" # 输入音频
>     tensor_to_video(dummy_tensor, output_video_file, audio_source, fps=25)
> ```

我也发现了这个问题，可以查看一下这个文件 conda_env/lib/python3.10/site-packages/moviepy/tools.py ，编码aac对应的应该是mp4

**Comment by DBDXSS** [comment]
extensions_dict = { "mp4":  {'type':'video', 'codec':['libx264','libmpeg4', 'aac']},
                    'ogv':  {'type':'video', 'codec':['libtheora']},
                    'webm': {'type':'video', 'codec':['libvpx']},
                    'avi':  {'type':'video'},
                    'mov':  {'type':'video'},

                    'ogg':  {'type':'audio', 'codec':['libvorbis']},
                    'mp3':  {'type':'audio', 'codec':['libmp3lame']},
                    'wav':  {'type':'audio', 'codec':['pcm_s16le', 'pcm_s24le', 'pcm_s32le']},
                    'm4a':  {'type':'audio', 'codec':['libfdk_aac']}
                  }

**Comment by piwawa** [comment]
![image](https://github.com/user-attachments/assets/e3a9299b-8b93-4481-a146-a5d7e6b1fc9b)

**Comment by DBDXSS** [comment]
可以尝试一下debug，在conda_env/lib/python3.10/site-packages/moviepy/video/VideoClip.py 的278行开始插入断点，查看一下原因

**Comment by DBDXSS** [comment]
> ![image](https://private-user-images.githubusercontent.com/46926496/370658757-e3a9299b-8b93-4481-a146-a5d7e6b1fc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTg2NTMsIm5iZiI6MTcyNzI1ODM1MywicGF0aCI6Ii80NjkyNjQ5Ni8zNzA2NTg3NTctZTNhOTI5OWItOGI5My00NDgxLWExNDYtYTVkN2U2YjFmYzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZjFmYzA0M2Y2ZjI5MGFlZDJkM2Y3YmRlOTZhNDY3MGIwNmI2YTU4OGRhZTdlMzE4OWVkNGI5YjQ4ZTM4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iO2hDQ5KUyK57ZWlb-o9iSdxA-37Sm7wtMCGd_qZ030)

下面代码也是来自conda_env/lib/python3.10/site-packages/moviepy/tools.py，您可以对比一下，这里传入的codec是acc，您可以看一下这一步传入的是什么：

```
extensions_dict = { "mp4":  {'type':'video', 'codec':['libx264','libmpeg4', 'aac']},
                    'ogv':  {'type':'video', 'codec':['libtheora']},
                    'webm': {'type':'video', 'codec':['libvpx']},
                    'avi':  {'type':'video'},
                    'mov':  {'type':'video'},

                    'ogg':  {'type':'audio', 'codec':['libvorbis']},
                    'mp3':  {'type':'audio', 'codec':['libmp3lame']},
                    'wav':  {'type':'audio', 'codec':['pcm_s16le', 'pcm_s24le', 'pcm_s32le']},
                    'm4a':  {'type':'audio', 'codec':['libfdk_aac']}
                  }

for ext in ["jpg", "jpeg", "png", "bmp", "tiff"]:
    extensions_dict[ext] = {'type':'image'}


def find_extension(codec):
    if codec in extensions_dict:
        # codec is already the extension
        return codec

    for ext,infos in extensions_dict.items():
        if codec in infos.get('codec', []):
            return ext
    raise ValueError(
        "The audio_codec you chose is unknown by MoviePy. "
        "You should report this. In the meantime, you can "
        "specify a temp_audiofile with the right extension "
        "in write_videofile."
    )
```

**Comment by DBDXSS** [comment]
如果这还不能解决您的问题，可以尝试修改源码指定为mp4格式或者将acc修改为mp4

**Comment by piwawa** [comment]
![image](https://github.com/user-attachments/assets/193ddc99-5cff-4a72-9a1e-a35fdc7f4004)
发现问题了，在调用  write_videofile 方法时不知道怎么没有传入 fps ，我换了个环境装了同样版本的 moviepy 居然又正常，可以传入 fps，不知道啥情况

**Comment by DBDXSS** [comment]
可能是装包的时候使用了pip镜像？解决了就好

**Comment by piwawa** [comment]
Update! 
通过运行以下两条命令解决该问题
```
pip uninstall moviepy decorator
pip install moviepy
```
